/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/cases': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * List Cases
     * @description Tenant-wide, distinct from /review/cases (the needs_review-only queue) -- the admin
     *     console's case list, not the reviewer's.
     */
    get: operations['list_cases_cases_get']
    put?: never
    /** Create Case */
    post: operations['create_case_cases_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/cases/{case_id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get Case */
    get: operations['get_case_cases__case_id__get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/review/cases': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * List Review Queue
     * @description The review queue *is* `cases WHERE status = 'needs_review'` (see PLAN.md) -- there's no
     *     separate queue table to keep in sync.
     */
    get: operations['list_review_queue_review_cases_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/review/cases/{case_id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get Review Case Detail
     * @description Everything a reviewer needs to actually make a decision -- the queue list endpoint above
     *     deliberately only has enough to render a row; this one composes the case with its
     *     extraction, face match, and sanctions hits, which the admin-facing GET /cases doesn't need
     *     and doesn't return.
     */
    get: operations['get_review_case_detail_review_cases__case_id__get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/review/cases/{case_id}/claim': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Claim Review Case
     * @description Advisory only (see PLAN.md): claiming is a UI signal, not a lock -- the decision
     *     endpoint below doesn't require a prior claim, so a stale/abandoned claim can never block a
     *     case from being decided. Re-claiming (by the same or a different reviewer) simply
     *     overwrites the previous claim.
     */
    post: operations['claim_review_case_review_cases__case_id__claim_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/review/cases/{case_id}/decision': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Submit Review Decision */
    post: operations['submit_review_decision_review_cases__case_id__decision_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api-keys': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** List Api Keys */
    get: operations['list_api_keys_api_keys_get']
    put?: never
    /** Create Api Key */
    post: operations['create_api_key_api_keys_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api-keys/{key_id}/revoke': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Revoke Api Key */
    post: operations['revoke_api_key_api_keys__key_id__revoke_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/reviewers': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** List Reviewers */
    get: operations['list_reviewers_reviewers_get']
    put?: never
    /** Create Reviewer */
    post: operations['create_reviewer_reviewers_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/reviewers/{reviewer_id}/revoke': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Revoke Reviewer */
    post: operations['revoke_reviewer_reviewers__reviewer_id__revoke_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/webhooks': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** List Webhooks */
    get: operations['list_webhooks_webhooks_get']
    put?: never
    /** Create Webhook */
    post: operations['create_webhook_webhooks_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/webhooks/{webhook_id}/disable': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Disable Webhook */
    post: operations['disable_webhook_webhooks__webhook_id__disable_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/webhooks/{webhook_id}/deliveries': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** List Webhook Deliveries */
    get: operations['list_webhook_deliveries_webhooks__webhook_id__deliveries_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/dashboard/summary': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get Dashboard Summary */
    get: operations['get_dashboard_summary_dashboard_summary_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    /** ApiKeyCreateRequest */
    ApiKeyCreateRequest: {
      /** Name */
      name: string
    }
    /** ApiKeyCreateResponse */
    ApiKeyCreateResponse: {
      /** Id */
      id: string
      /** Name */
      name: string
      /**
       * Created At
       * Format: date-time
       */
      created_at: string
      /** Revoked At */
      revoked_at: string | null
      /** Raw Key */
      raw_key: string
    }
    /** ApiKeyResponse */
    ApiKeyResponse: {
      /** Id */
      id: string
      /** Name */
      name: string
      /**
       * Created At
       * Format: date-time
       */
      created_at: string
      /** Revoked At */
      revoked_at: string | null
    }
    /** CaseCreateRequest */
    CaseCreateRequest: {
      /** Subject Name */
      subject_name: string
      /** Subject Dob */
      subject_dob?: string | null
      id_document: components['schemas']['DocumentUpload']
      selfie: components['schemas']['DocumentUpload']
    }
    /** CaseCreateResponse */
    CaseCreateResponse: {
      /** Case Id */
      case_id: string
      /**
       * Status
       * @enum {string}
       */
      status: 'pending' | 'processing' | 'needs_review' | 'approved' | 'rejected'
      id_document: components['schemas']['UploadTarget']
      selfie: components['schemas']['UploadTarget']
    }
    /** CaseResponse */
    CaseResponse: {
      /** Case Id */
      case_id: string
      /**
       * Status
       * @enum {string}
       */
      status: 'pending' | 'processing' | 'needs_review' | 'approved' | 'rejected'
      /** Subject Name */
      subject_name: string
      /** Subject Dob */
      subject_dob: string | null
      /** Decision */
      decision: ('approved' | 'rejected') | null
      /**
       * Created At
       * Format: date-time
       */
      created_at: string
      /** Risk Score */
      risk_score: number | null
    }
    /** DashboardActivityItem */
    DashboardActivityItem: {
      /** Case Id */
      case_id: string
      /** Subject Name */
      subject_name: string
      /** Event */
      event: string
      /**
       * At
       * Format: date-time
       */
      at: string
    }
    /** DashboardCaseVolumePoint */
    DashboardCaseVolumePoint: {
      /**
       * Date
       * Format: date
       */
      date: string
      /** Count */
      count: number
    }
    /** DashboardSummaryResponse */
    DashboardSummaryResponse: {
      /** Status Counts */
      status_counts: {
        [key: string]: number
      }
      /** Cases Last 30 Days */
      cases_last_30_days: components['schemas']['DashboardCaseVolumePoint'][]
      /** Recent Activity */
      recent_activity: components['schemas']['DashboardActivityItem'][]
    }
    /** DocumentUpload */
    DocumentUpload: {
      /** Content Type */
      content_type: string
      /** Size Bytes */
      size_bytes: number
    }
    /** ExtractionDetail */
    ExtractionDetail: {
      /** Document Id */
      document_id: string
      /**
       * Method
       * @enum {string}
       */
      method: 'mrz' | 'vlm'
      /** Confidence */
      confidence: number
      /** Valid */
      valid: boolean
      /** Full Name */
      full_name: string | null
      /** Date Of Birth */
      date_of_birth: string | null
      /** Document Number */
      document_number: string | null
      /** Nationality */
      nationality: string | null
      /** Expiry Date */
      expiry_date: string | null
    }
    /** FaceMatchDetail */
    FaceMatchDetail: {
      /** Similarity Score */
      similarity_score: number | null
      /** Reason */
      reason: string | null
    }
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components['schemas']['ValidationError'][]
    }
    /** ReviewCaseDetailResponse */
    ReviewCaseDetailResponse: {
      /** Case Id */
      case_id: string
      /**
       * Status
       * @enum {string}
       */
      status: 'pending' | 'processing' | 'needs_review' | 'approved' | 'rejected'
      /** Subject Name */
      subject_name: string
      /** Subject Dob */
      subject_dob: string | null
      /** Decision */
      decision: ('approved' | 'rejected') | null
      /**
       * Created At
       * Format: date-time
       */
      created_at: string
      /** Risk Score */
      risk_score: number | null
      /** Id Document Url */
      id_document_url: string | null
      /** Selfie Url */
      selfie_url: string | null
      extraction: components['schemas']['ExtractionDetail'] | null
      face_match: components['schemas']['FaceMatchDetail'] | null
      /** Sanctions Hits */
      sanctions_hits: components['schemas']['SanctionsHitDetail'][]
    }
    /** ReviewDecisionRequest */
    ReviewDecisionRequest: {
      /**
       * Decision
       * @enum {string}
       */
      decision: 'approved' | 'rejected' | 'escalated'
      /** Justification */
      justification: string
    }
    /** ReviewDecisionResponse */
    ReviewDecisionResponse: {
      /** Case Id */
      case_id: string
      /** Decision */
      decision: string
      /** Reviewer Id */
      reviewer_id: string
      /**
       * Decided At
       * Format: date-time
       */
      decided_at: string
    }
    /** ReviewQueueCase */
    ReviewQueueCase: {
      /** Case Id */
      case_id: string
      /** Subject Name */
      subject_name: string
      /** Subject Dob */
      subject_dob: string | null
      /** Risk Score */
      risk_score: number | null
      /**
       * Created At
       * Format: date-time
       */
      created_at: string
      /** Claimed By Reviewer Id */
      claimed_by_reviewer_id: string | null
      /** Claimed At */
      claimed_at: string | null
    }
    /** ReviewerCreateRequest */
    ReviewerCreateRequest: {
      /** Email */
      email: string
      /**
       * Role
       * @default reviewer
       * @enum {string}
       */
      role: 'reviewer' | 'admin' | 'auditor'
    }
    /** ReviewerCreateResponse */
    ReviewerCreateResponse: {
      /** Id */
      id: string
      /** Email */
      email: string
      /**
       * Role
       * @enum {string}
       */
      role: 'reviewer' | 'admin' | 'auditor'
      /**
       * Created At
       * Format: date-time
       */
      created_at: string
      /** Revoked At */
      revoked_at: string | null
      /** Raw Token */
      raw_token: string
    }
    /** ReviewerResponse */
    ReviewerResponse: {
      /** Id */
      id: string
      /** Email */
      email: string
      /**
       * Role
       * @enum {string}
       */
      role: 'reviewer' | 'admin' | 'auditor'
      /**
       * Created At
       * Format: date-time
       */
      created_at: string
      /** Revoked At */
      revoked_at: string | null
    }
    /** SanctionsHitDetail */
    SanctionsHitDetail: {
      /** List Source */
      list_source: string
      /** Matched Name */
      matched_name: string
      /** Match Score */
      match_score: number
      /**
       * Method
       * @enum {string}
       */
      method: 'vector' | 'phonetic'
    }
    /** UploadTarget */
    UploadTarget: {
      /** Document Id */
      document_id: string
      /** S3 Key */
      s3_key: string
      /** Upload Url */
      upload_url: string
    }
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[]
      /** Message */
      msg: string
      /** Error Type */
      type: string
      /** Input */
      input?: unknown
      /** Context */
      ctx?: Record<string, never>
    }
    /** WebhookCreateRequest */
    WebhookCreateRequest: {
      /** Url */
      url: string
    }
    /** WebhookCreateResponse */
    WebhookCreateResponse: {
      /** Id */
      id: string
      /** Url */
      url: string
      /**
       * Created At
       * Format: date-time
       */
      created_at: string
      /** Disabled At */
      disabled_at: string | null
      /** Secret */
      secret: string
    }
    /** WebhookDeliveryResponse */
    WebhookDeliveryResponse: {
      /** Id */
      id: string
      /** Webhook Id */
      webhook_id: string
      /** Case Id */
      case_id: string
      /** Event Type */
      event_type: string
      /**
       * Status
       * @enum {string}
       */
      status: 'pending' | 'delivered' | 'failed'
      /** Attempt Count */
      attempt_count: number
      /** Last Attempted At */
      last_attempted_at: string | null
    }
    /** WebhookResponse */
    WebhookResponse: {
      /** Id */
      id: string
      /** Url */
      url: string
      /**
       * Created At
       * Format: date-time
       */
      created_at: string
      /** Disabled At */
      disabled_at: string | null
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  list_cases_cases_get: {
    parameters: {
      query?: {
        status?: ('pending' | 'processing' | 'needs_review' | 'approved' | 'rejected') | null
      }
      header?: {
        authorization?: string | null
      }
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['CaseResponse'][]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  create_case_cases_post: {
    parameters: {
      query?: never
      header?: {
        'Idempotency-Key'?: string | null
        authorization?: string | null
      }
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['CaseCreateRequest']
      }
    }
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['CaseCreateResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  get_case_cases__case_id__get: {
    parameters: {
      query?: never
      header?: {
        authorization?: string | null
      }
      path: {
        case_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['CaseResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  list_review_queue_review_cases_get: {
    parameters: {
      query?: never
      header?: {
        authorization?: string | null
      }
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ReviewQueueCase'][]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  get_review_case_detail_review_cases__case_id__get: {
    parameters: {
      query?: never
      header?: {
        authorization?: string | null
      }
      path: {
        case_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ReviewCaseDetailResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  claim_review_case_review_cases__case_id__claim_post: {
    parameters: {
      query?: never
      header?: {
        authorization?: string | null
      }
      path: {
        case_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ReviewQueueCase']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  submit_review_decision_review_cases__case_id__decision_post: {
    parameters: {
      query?: never
      header?: {
        authorization?: string | null
      }
      path: {
        case_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['ReviewDecisionRequest']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ReviewDecisionResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  list_api_keys_api_keys_get: {
    parameters: {
      query?: never
      header?: {
        authorization?: string | null
      }
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ApiKeyResponse'][]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  create_api_key_api_keys_post: {
    parameters: {
      query?: never
      header?: {
        authorization?: string | null
      }
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['ApiKeyCreateRequest']
      }
    }
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ApiKeyCreateResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  revoke_api_key_api_keys__key_id__revoke_post: {
    parameters: {
      query?: never
      header?: {
        authorization?: string | null
      }
      path: {
        key_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ApiKeyResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  list_reviewers_reviewers_get: {
    parameters: {
      query?: never
      header?: {
        authorization?: string | null
      }
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ReviewerResponse'][]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  create_reviewer_reviewers_post: {
    parameters: {
      query?: never
      header?: {
        authorization?: string | null
      }
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['ReviewerCreateRequest']
      }
    }
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ReviewerCreateResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  revoke_reviewer_reviewers__reviewer_id__revoke_post: {
    parameters: {
      query?: never
      header?: {
        authorization?: string | null
      }
      path: {
        reviewer_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ReviewerResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  list_webhooks_webhooks_get: {
    parameters: {
      query?: never
      header?: {
        authorization?: string | null
      }
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['WebhookResponse'][]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  create_webhook_webhooks_post: {
    parameters: {
      query?: never
      header?: {
        authorization?: string | null
      }
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['WebhookCreateRequest']
      }
    }
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['WebhookCreateResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  disable_webhook_webhooks__webhook_id__disable_post: {
    parameters: {
      query?: never
      header?: {
        authorization?: string | null
      }
      path: {
        webhook_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['WebhookResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  list_webhook_deliveries_webhooks__webhook_id__deliveries_get: {
    parameters: {
      query?: never
      header?: {
        authorization?: string | null
      }
      path: {
        webhook_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['WebhookDeliveryResponse'][]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  get_dashboard_summary_dashboard_summary_get: {
    parameters: {
      query?: never
      header?: {
        authorization?: string | null
      }
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['DashboardSummaryResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
}
